<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ecommerce</groupId>
    <artifactId>ecommerce-project</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <modules>
        <module>EcomOrderService</module>
        <module>EcomUserAuthService</module>
        <module>EcomPaymentService</module>
        <module>EcomProductService</module>
        <module>discovery-service</module>
    </modules>

</project>
