spring.application.name=EcomInventoryService
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApfb+OYxkXCZF23mZTvbRSwCCgtxtqOJEkNEztxP1laFpyMtPEzBHMFn4OLiKpwPVcpHCvoRgO/56guI6IufXpGiuQUYTgReoxdWP1ibhTmjJFWSKMJEaqsMnYjzPjr1A7XATolQasi+ciyo+N1cA+g5A46P0anl6BEQAaeYESmZDGhYYCaFCcTEcVZXlldH/DvLDfHpdnx9XApQvQc/LwhCmb50gEGjUTLLiqORyob+khjh3gAdJngU67GIZrnHV6+zDuuDRf4i8cFFsSlIEY7dgPxu5J/6TMbzzEeDF49aQuB042vJtrNeilTYqIKx7//0zhplkFTVVOITNdIG/4QIDAQAB

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
